[package]
name = "ot-update"
description = "Self-updater for open-task. Automatic updates are opt-in."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
