[package]
name = "ot-app"
description = "open-task: a fully open source, high performance task manager."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
default-run = "open-task"

[[bin]]
name = "open-task"
path = "src/main.rs"

[dependencies]
ot-model.workspace = true
ot-probe.workspace = true
ot-core.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(windows)'.dependencies]
ot-shell-win.workspace = true

[lints]
workspace = true
